name: Bug Report
description: Create a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees:
  - tristankechlo
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is, and how it appeared.
      placeholder: |
        Tell us what happened!
        How did you produce the bug?
        What should have happened?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. If you have screenshots you can attach them here.
    validations:
      required: false
